### PR TITLE
Group fix for trinkets not loading correctly

### PR DESCRIPTION
**Pull request by tsukori**
fixing issue #530

### CODE REVIEW

**Comment by tsukori** [comment]
@eah13  please doublecheck that this pull request won't destroy our class page. I'm particularly worried about the top two commits saying "merge pull request from silshack/gh-pages"

If it is a problem I can just do 5 pull requests for each of the problems.

**Comment by eah13** [comment]
Nice!  Style points for including them all in one PR.

The 'merge' pull requests are you pulling in changes from silshack/gh-pages to tsukori/gh-pages.  They're normal when you do this sort of thing.

Nice work using your own fork too.  The only thing I'd suggest for next time is to make a non-gh-pages branch in your fork.  Do a PR from silshack/gh-pages to this new branch, make your changes there, then PR back to silshack/gh-pages.That way it's easier to know that the 'master' branch is identical to the one in our repo.  When you commit to tsukori/gh-pages (as opposed to say `tsukori/iframe-fixes`) it could create problems if your commits are never accepted upstream. 

No problem this time, just something to know for other open source projects.

**Comment by eah13** [comment]
:horse:

**Comment by eah13** [comment]
Another thing to note: since you have commit access to the silshack repo, you can create a new branch straight in this repo.  By default this new branch will be identical to silshack/gh-pages, saving you a merge.  But the way you did it in your fork is analogous to what'll go on in an open source project where you're not a committer.

**Pull request merged**
