### PR TITLE
Create Ruotong's Ch3 Conditionals Exercises Post

### PR DESCRIPTION
**Pull request by izayak**

### CODE REVIEW

**Comment by izayak** [comment]
What's the problem? :confused:

**Comment by eah13** [comment]
@izayak I don't believe this is your fault- your post looks good.  I'm going to merge and I believe the problem will resolve itself.  It might have been an invalid post that was in the repo when you created your branch that has since been fixed.

**Comment by izayak** [comment]
Is this good now? Do I need to do something? @eah13

**Comment by eah13** [comment]
Yes, you need to create a pull request that moves (renames) your post into your `izayak` folder.  See #234

**Pull request merged**
