### PR TITLE
Becca's Turtle Post

### PR DESCRIPTION
**Pull request by RhymesWithMecca**
These are my turtle programs.  I enjoyed coding and troubleshooting.  I think I'll need a bit to get used to pull requests and merging.

### CODE REVIEW

**Comment by eah13** [comment]
@RhymesWithMecca Looks good.  I think you'll want to add some reflections to the post.  Your pull request description here on github.com won't show up on our silshack site.

**Comment by RhymesWithMecca** [comment]
@eah13 Thanks for your comment!  I can't figure out how to re-open the post to edit it.  It tells me that I must be "on a branch" to edit the post, and I'm not sure what that means.

**Comment by eah13** [comment]
I've got a quick video I'll post with a walk-thru.  

In the meantime, even though there's a notice at the top, you'll find a green button at the bottom if you scroll down.  When you find what seems like a barrier, keep going and see if you can go around it :)

We'll go over branches later in the class and I talk a little about them in the video.  Basically, a branch is a revision of our code.  A pull request is a social wrapper around a comparison between any two branches (usually your changes and the main branch).

**Comment by RhymesWithMecca** [comment]
@eah13 I watched the video and there are hopefully reflections in the post now.

**Comment by eah13** [comment]
:star2:

**Pull request merged**
