### PR TITLE
Drawing app milestones

### PR DESCRIPTION
**Pull request by jamesma560**

### CODE REVIEW

**Comment by eah13** [comment]
@EternalFootman @jamesma560 check the location of the file in this PR. Go to the main repo and James can fix it with a PR that moves it to the right post

**Comment by eah13** [comment]
Also, referencing #627 for clarity.

**Comment by jamesma560** [comment]
@eah13 apologies but I'm not clear on what I should do. So are you saying I should resubmit it with another PR, but move the PR somewhere else?

**Comment by eah13** [comment]
You need to move the file so it's in the right place for it to display. Via
a PR. It's not in the _posts folder.

**Pull request merged**
