### PR TITLE
Sharing my first two turtle programs

### PR DESCRIPTION
**Pull request by jamesma560**

### CODE REVIEW

**Comment by eah13** [comment]
Looks good.  I'm assuming you'll return to this PR and add a reflection.

**Comment by jamesma560** [comment]
Yes. For some strange reason I got confused and thought the reflection was supposed to be a second post, but I'll add a reflection to this one.

**Comment by eah13** [comment]
No worries!

**Comment by eah13** [comment]
Nice.  Way to stick with the same theme and develop it.  And good reflection.  I'm not sure about `title()`\- could you share a link on that? :rocket:

**Pull request merged**
