### PR TITLE
Posting my treasure hunting turtle.

### PR DESCRIPTION
**Pull request by ColinRNickels**
:crown:  -- That's the closest to treasure I could find.

### CODE REVIEW

**Comment by namagic** [comment]
code ran smoothly :+1: with useful comments :+1:

**Comment by namagic** [comment]
title doesn't have quotes though

**Comment by namagic** [comment]
Allows user to input integers greater than 100 and less than 100, not necessarily a mistake, but just noted

**Comment by ColinRNickels** [comment]
Added those vital quotes. :tada:

**Pull request merged**
