### PR TITLE
Add Lingjie's Turtle HWs

### PR DESCRIPTION
**Pull request by clairewlj**

### CODE REVIEW

**Comment by clairewlj** [comment]
sorry but I forget how to change before merging...I just want to add a title to it

**Comment by eah13** [comment]
No problem.  You'll also want to add a reflection.

To change this file, go to the files tab of this pull request then use the pencil icon to edit.  Your commit should then show up in this pull request.

**Comment by clairewlj** [comment]
Thanks! But I'm not sure about what the reflection is. Oh is it just my comment on the exercise? 
And I also have another question that if I change my code on trinket after my post has already been merged, will the code change in github change as well?

**Comment by eah13** [comment]
Nice drawing!  And good job on your reflection.

Updates to your trinket will display in the github post, though in this case your trinket was due a while ago so you shouldn't be updating it.

:ice_cream:

**Pull request merged**
